[build]
  command = "bundle install && npm install && bin/bridgetown deploy"
  publish = "output"

[build.environment]
  RUBY_VERSION = "3.4.7"
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
